# .github/workflows/update.yml
name: Ultra Block Config Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Shadowrocket config
        run: |
          mkdir -p lists
          curl -sSL https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o lists/hosts.txt || true
          curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt -o lists/adguard.txt || true

          # Начало конфигурации Shadowrocket
          echo "[General]" > adblock2025_ultra_opt.conf
          echo "bypass-system = true" >> adblock2025_ultra_opt.conf
          echo "skip-proxy = 127.0.0.1, localhost" >> adblock2025_ultra_opt.conf
          echo "" >> adblock2025_ultra_opt.conf
          echo "[Rule]" >> adblock2025_ultra_opt.conf

          # Объединяем блок-листы в формате DOMAIN
          cat lists/*.txt | grep -v '^#' | grep -v '^$' | sort -u >> adblock2025_ultra_opt.conf

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add adblock2025_ultra_opt.conf
          git commit -m "Auto-update ultra blocklists $(date -u)" || echo "No changes"

      - name: Push changes
        run: git push origin HEAD:main