name: Ultra Block Config Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"   # каждый день в 03:00 UTC

permissions:
  contents: write

jobs:
  update-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download blocklists and merge
        run: |
          mkdir -p lists
          curl -sSL https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts -o lists/hosts.txt
          curl -sSL https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt -o lists/adguard.txt
          curl -sSL https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt -o lists/adguard_en.txt
          curl -sSL https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt -o lists/adaway.txt
          curl -sSL https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt -o lists/nocoin.txt

          echo "# Ultra AdBlock Config (auto-updated)" > adblock2025_ultra_opt.conf
          echo "# Updated: $(date -u)" >> adblock2025_ultra_opt.conf
          echo "" >> adblock2025_ultra_opt.conf

          # объединение всех списков
          cat lists/*.txt | grep -v '^#' | sort -u >> adblock2025_ultra_opt.conf

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add adblock2025_ultra_opt.conf
          git commit -m "Auto-update ultra blocklists $(date -u)" || echo "No changes"

      - name: Push changes
        run: |
          git push origin HEAD:main
